DROP TABLE IF EXISTS merchant;
DROP TABLE IF EXISTS buyer;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS sub_category;
DROP TABLE IF EXISTS bank;
DROP TABLE IF EXISTS state;
DROP TABLE IF EXISTS orders;


CREATE TABLE merchant (
id INT(200) PRIMARY KEY AUTO_INCREMENT NOT NULL,
merchant_id VARCHAR(50) NOT NULL UNIQUE,
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
company_name VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(200) NOT NULL,
phone VARCHAR(11) NOT NULL UNIQUE,
address TEXT NOT NULL,
state INT(100) NOT NULL,
logo VARCHAR(100) NOT NULL,
about TEXT,
account_name VARCHAR(100) NOT NULL,
account_number VARCHAR(20) NOT NULL,
bank INT(100) NOT NULL,
date_created DATETIME NOT NULL,
date_updated DATETIME NOT NULL);

CREATE TABLE buyer (
id INT(200) PRIMARY KEY AUTO_INCREMENT NOT NULL,
buyer_id VARCHAR(200) NOT NULL UNIQUE,
fname VARCHAR(50) NOT NULL,
lname  VARCHAR(50) NOT NULL,
email VARCHAR(200) NOT NULL,
password VARCHAR(200) NOT NULL,
phone VARCHAR(11) NOT NULL UNIQUE,
address TEXT NOT NULL,
state VARCHAR(20) NOT NULL,
date_created DATETIME NOT NULL,
date_updated DATETIME NOT NULL);

CREATE TABLE product (
id INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
product_id VARCHAR(200) NOT NULL UNIQUE,
product_name VARCHAR(100) NOT NULL,
product_price DOUBLE NOT NULL,
product_category INT(100) NOT NULL,
product_sub_category INT(100),
product_negotiable ENUM ("true","false") NOT NULL DEFAULT "false",
product_discount DOUBLE,
date_created DATETIME NOT NULL,
date_updated DATETIME NOT NULL);

CREATE TABLE category (
id INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
cat_name VARCHAR(100) NOT NULL UNIQUE,
date_created DATETIME NOT NULL,
date_updated DATETIME NOT NULL);

CREATE TABLE sub_category (
id INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
cat_id INT(100) NOT NULL,
sub_cat_name VARCHAR(100) NOT NULL UNIQUE,
date_created DATETIME NOT NULL,
date_updated DATETIME NOT NULL);

CREATE TABLE bank (
id INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
bank_name VARCHAR(200) NOT NULL);

CREATE TABLE state (
id INT(100) PRIMARY KEY AUTO_INCREMENT NOT NULL,
state_name VARCHAR(100) NOT NULL);

CREATE TABLE orders (
id INT(200) PRIMARY KEY AUTO_INCREMENT NOT NULL,
product_id VARCHAR(200) NOT NULL,
product_name VARCHAR(100) NOT NULL,
product_price DOUBLE(100,2) NOT NULL,
order_quantity INT(11) NOT NULL,
order_total INT(100) NOT NULL,
buyer_id VARCHAR(200) NOT NULL,
seller_id VARCHAR(200) NOT NULL,
pay_on_delivery ENUM ("true","false") NOT NULL DEFAULT "false",
order_date DATETIME NOT NULL);
